# Generated by Django 6.0.4 on 2026-05-06 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="currency",
            field=models.CharField(
                choices=[("USD", "Dollar"), ("EUR", "Euro"), ("RUB", "Ruble")],
                default="EUR",
                max_length=3,
            ),
        ),
    ]
