# Generated by Django 6.0.4 on 2026-09-14 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0002_wallet_currency"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="income",
            options={
                "ordering": ["-date", "-created_at"],
                "verbose_name": "Income",
                "verbose_name_plural": "Incomes",
            },
        ),
        migrations.AlterModelOptions(
            name="transaction",
            options={
                "ordering": ["-date", "-created_at"],
                "verbose_name": "Transaction",
                "verbose_name_plural": "Transactions",
            },
        ),
    ]
