# Generated by Django 6.0.4 on 2026-09-14 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0003_alter_income_options_alter_transaction_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="expensecategory",
            name="category_type",
            field=models.CharField(
                choices=[("stable", "Stable"), ("floating", "Floating")],
                default="floating",
                max_length=8,
            ),
        ),
    ]
