# Generated by Django 6.0.4 on 2026-04-16 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="expensecategory",
            options={
                "verbose_name": "Expense Category",
                "verbose_name_plural": "Expense Categories",
            },
        ),
        migrations.AlterModelOptions(
            name="income",
            options={"verbose_name": "Income", "verbose_name_plural": "Incomes"},
        ),
        migrations.AlterModelOptions(
            name="incomecategory",
            options={
                "verbose_name": "Income Category",
                "verbose_name_plural": "Income Categories",
            },
        ),
        migrations.AlterModelOptions(
            name="transaction",
            options={
                "verbose_name": "Transaction",
                "verbose_name_plural": "Transactions",
            },
        ),
        migrations.AlterField(
            model_name="transaction",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
